version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: bionded-store-koel_web_1
      APP_PORT: 80

  web:
    image: phanan/koel:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/music:/music
      - ${APP_DATA_DIR}/covers:/var/www/html/public/img/storage
      - ${APP_DATA_DIR}/search-indexes:/var/www/html/storage/search-indexes
      - ./koel.env:/var/www/html/.env
    depends_on:
      - db

  db:
    image: mariadb:10.11
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: koel_root_secret
      MYSQL_DATABASE: koel
      MYSQL_USER: koel
      MYSQL_PASSWORD: koel_umbrel_secret
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql
